Clothes_Collection/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'main'

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_product
from main.views import delete_product, get_product_json, add_product_ajax, delete_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'), path('create-product', create_product, name='create_product'), path('xml/', show_xml, name='show_xml'), path('json/', show_json, name='show_json'), path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), path('register/', register, name='register'), path('login/', login_user, name='login'), path('logout/', logout_user, name='logout'), path('edit-product/<int:id>', edit_product, name='edit_product'), path('delete/<int:id>', delete_product, name='delete_product'), path('get-product/', get_product_json, name='get_product_json'),
path('create-product-ajax/', add_product_ajax, name='add_product_ajax'), path('create-product-ajax/', add_product_ajax, name='add_product_ajax'), path("delete-product-ajax/<int:id>", delete_product_ajax, name="delete_product_ajax")

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    price = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    has_preloved =  models.BooleanField(default=False)



    

   

   

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description"]
    class Preloved: 
        model = Product
        fields= []

main/views.py
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.http import HttpResponse
from django.core import serializers
from django.http import HttpResponseRedirect
from django.urls import reverse
from main.forms import ProductForm
from main.models import Product
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    item_count = products.count()

    context = {
        'name': request.user.username,
        'class': 'PBP KI', # Your PBP Class
        'products': products,
        'item_count': item_count,
        'last_login': request.COOKIES['last_login']

    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return redirect('main:login')

def edit_product(request, id):
    # Get product by ID
    product = Product.objects.get(pk = id)

    # Set product as instance of form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Save the form and return to home page
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data by ID
    product = Product.objects.get(pk=id)
    # Delete data
    product.delete()
    # Return to the main page
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, price=price, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_product_ajax(request, id):
    product = Product.objects.get(pk=id)
    product.delete()
    return HttpResponse(b"DELETED", status=201)

def preloved_product(request):
    

main/templates/create_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
   
    body {
        font-family: Arial, sans-serif;
        background-color: #FFC9D8; 
        color: #333;
        margin: 0;
        padding: 0;
    }

    h1 {
        color: #333; 
        text-align: center;
        margin: 20px 0;
    }

    form {
        max-width: 600px;
        margin: 0 auto;
        background-color: #fff; 
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

    table {
        width: 100%;
    }

    table tr td {
        padding: 10px;
    }

    input[type="submit"] {
        background-color: #333; 
        color: #FFC9D8; 
        border: none;
        border-radius: 5px;
        cursor: pointer;
        padding: 10px 20px;
        font-size: 16px;
    }

    input[type="submit"]:hover {
        background-color: #FFC9D8; 
        color: #333; 
    }

   

</style>

<h1>ADD NEW PRODUCT</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
    /* Custom CSS for the Edit Product form */
    body {
        font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        background-color: rgba(255, 201, 216, 0.5);
        color: #333;
        margin: 0;
        padding: 0;
    }

    h1 {
        color: #333; /* Text color */
        text-align: center;
        margin: 20px 0;
    }

    form {
        max-width: 600px;
        margin: 0 auto;
        background-color: #fff; /* Form background color */
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

    table {
        width: 100%;
    }

    table tr td {
        padding: 10px;
    }

    input[type="submit"] {
        background-color: #333; /* Button background color */
        color: #FFC9D8; /* Button text color */
        border: none;
        border-radius: 5px;
        cursor: pointer;
        padding: 10px 20px;
        font-size: 16px;
        
    }

    input[type="submit"]:hover {
        background-color: #FFC9D8; /* Hover background color */
        color: #333; /* Hover text color */
    }

    /* Add more custom styles as needed */

</style>

<h1>EDIT PRODUCT</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-size: cover;
        background-color: #FFC9D8;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
    }


    header {
        color: #333;
    }


    .login {
        text-align: center;
        padding: 40px;
        background-color: #333;
        max-width: 400px;
        width: 100%;
        border-radius: 10px;
        margin: 0 auto;
        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
    }

    .login h1 {
        font-size: 28px;
        font-weight: bold;
        text-transform: uppercase;
        color: rgb(251, 251, 251);
        margin-bottom: 20px;
    }

    .login form {
        margin-top: 30px;
        margin-bottom: 20px;
    }

    .login .center-text {
        text-align: left;
    }

    .login input.form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    .login .btn.login_btn {
        background-color: #FFC9D8;
        color: #333;
        padding: 9px 50px;
        border: none;
        border-radius: 5px;
        font-size: 18px;
        cursor: pointer;
        
    }

    .register-link {
        font-size: 14px;
        color: #fff;
        text-decoration: none;
    }

    .register-link:hover {
        text-decoration: underline;
    }

    .no-account{
        font-size: 14px;
        color: #FFC9D8;
        text-decoration: none;
    }
</style>

<header>
   <h1 style="padding-left: 100px; font-size: 100px;">H E L L O .</h1>
</header>

<div class="login">
    <h1>LOGIN</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <div class="center-text">
    
            <input type="text" name="username" id="username" placeholder="Username" class="form-control">
        </div>

        <div class="center-text">
           
            <input type="password" name="password" id="password" placeholder="Password" class="form-control">
        </div>

        <div>
            <input class="btn login_btn" type="submit" value="Login">
        </div>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p class="no-account" >Don't have an account yet? <a href="{% url 'main:register' %}" class="register-link">Register Now</a></p>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<style>

    body {
        font-family: Arial, sans-serif;
        background-color: rgba(255, 201, 216, 0.5);
        color: #333;
        margin: 0;
        padding: 0;
    }

    nav {
        background-color: #333;
        color: #fff;
        padding: 20px;
        text-align: center;
    }

    .container {
        max-width: 1400px;
        margin: 20px auto;
        padding: 40px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

    .product {
        border: 1px solid #ddd;
        padding: 20px;
        margin: 20px;
        text-align: center;
        background-color: #fff;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    .product img {
        max-width: 100%;
        height: auto;
    }

    .product h3 {
        font-size: 24px;
        color: #333; 
    }

    .product p {
        font-size: 18px;
        color: #777;
    }

   
    .btn {
        background-color: #333;
        color: #fff;
        padding: 5px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
        font-size: 15px;
    }

    .btn:hover {
        background-color: #555; 
    }

   
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        background-color: #fff;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 12px;
        text-align: left;
        color: #333;
    }

    th {
        background-color: #f2f2f2;
        color: #555;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    
    table button {
        background-color: #333;
        color: #fff;
        padding: 8px 16px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
        font-size: 14px;
    }

    table button:hover {
        background-color: #555;
    }

    footer {
        background-color: #333;
        color: #fff;
        padding: 20px;
        text-align: center;
        position: fixed;
        bottom: 0;
        left: 0;
        width: 100%;
    }

    
    .label-value {
        display: flex;
        justify-content: space-between;
    }

    
    .label-value h5 {
        margin-right: 10px;
    }

    tr.preloved-row{
        background-color: lightgreen;
    }
    
</style>

<nav>
    <h1>H E L ' S</h1>
</nav>
</tr>
<div class="container">

    <h5 style="text-align: center; font-size: 27px; font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif"> YOUR CART</h5>

    <table id="product_table"></table>
    <!--table>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Actions</th>

        </tr>

        {% for product in products %}
        <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.date_added }}</td>
            
            <td>
                <a href="{% url 'main:edit_product' product.pk %}">
                    <button class="btn">Edit</button>
                </a>
                <a href="{% url 'main:delete_product' product.pk %}">
                    <button class="btn">Delete</button>
                </a>
            </td>
            
        </tr>
        {% endfor %}
    </table -->
    
    <br />

    <a href="{% url 'main:create_product' %}">
        <button class="btn">Add New Product</button>
    </a>
    
    <a href="{% url 'main:logout' %}">
        <button class="btn">Logout</button>
    </a>
          
</div>
<h5 style="font-size: 14px; text-align:center;">Last login session: {{ last_login }}</h5>
<footer>
    &copy; 2023 H E L ' s Collection. All rights reserved.
</footer>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString = `<tr>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Actions</th>
            
        </tr>`
        products.forEach((item) => {
            let prelovedClass = item.fields.has_preloved ? "preloved-row": ""
            htmlString += `
            <tr class = "${prelovedClass}">
            <td>${item.fields.name}</td>
            <td>${item.fields.price}</td>
            <td>${item.fields.description}</td>
            <td>${item.fields.date_added}</td>
            <td><button class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" onclick="deleteProduct(${item.pk})">
                Delete</button>
            </td>
            
        </tr>` 
        })
        
        document.getElementById("product_table").innerHTML = htmlString
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    function deleteProduct(id) {
      fetch("delete-product-ajax/" + id, {
        method: "POST"
      }).then(refreshProducts)

      document.getElementById("form").reset()
      return false
    }

    function prelovedProduct(id) {
      fetch("preloved-product-ajax/" + id, {
        method: "POST"
      }).then(refreshProducts)

      document.getElementById("form").reset()
      return false

</script>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
    <script>
        document.getElementById("button_add").onclick = addProduct;
    </script>
</div>


<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" >Add Product by AJAX</button>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
   
    body {
        background-color: rgba(255, 201, 216, 0.5);
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        font-family: Arial, sans-serif;
    }

    .login {
        text-align: center;
        padding: 40px;
        background-color: #fff;
        max-width: 400px;
        width: 100%;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
    }

    .login h1 {
        font-size: 28px;
        font-weight: bold;
        text-transform: uppercase;
        color: #333;
        margin-bottom: 20px;
    }

    .login form {
        margin-top: 20px;
    }

    .login input[type="text"],
    .login input[type="password"],
    .login input[type="submit"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #333;
        border-radius: 4px;
        font-size: 16px;
    }

    .login input[type="submit"] {
        background-color: #333;
        color: #fff;
        padding: 12px 0;
        border: none;
        border-radius: 4px;
        font-size: 18px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .login input[type="submit"]:hover {
        background-color: #FFC9D8;
    }

    .register-link {
        font-size: 14px;
        color: #007bff;
        text-decoration: none;
    }

    .register-link:hover {
        text-decoration: underline;
    }
</style>
<div class="login">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <tr>
            <td></td>
            <td><input type="submit" name="submit" value="Register" /></td>
        </tr>
    </form>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}